version: "3"

services:

  memcached:
    image: memcached:alpine
    ports:
      - 11211
    deploy:
      mode: replicated
      replicas: 3

  dalli:
    tty: true
    stdin_open: true
    build:
      context: .